### ISSUE TITLE
File not found: "vshader_shbin.h"

### ISSUE THREAD

**Issue by thomas-alrek** [BernardoGiordano/pp2d#14]
Hello. I was just trying to set up pp2d in my project. I have added the library as a submodule under this path in my project: `source/libs/pp2d`

In my main.c source file (located under `source/main.c`, I include it like this:

```c
#include "lib/pp2d/pp2d.h"
```

When I compile, I get this message:

```
source/lib/pp2d/pp2d.h:22:10: fatal error: vshader_shbin.h: No such file or directory
 #include "vshader_shbin.h"
```

I couldn't find this file in the pp2d folder. Is there something I am missing?

**Comment by BernardoGiordano** [comment]
You're missing rules to compile .pica files in the makefile. The shbin.h file will be created when you compile the .pica file

**Comment by thomas-alrek** [comment]
Ah, allright, thank you! I am quite new to this
