### ISSUE TITLE
[REQUEST] Create pp2d_set_3d(int)

### ISSUE THREAD

**Issue by Jolty95** [BernardoGiordano/pp2d#5]
Hi!

Do you please create that function? It should be something like: 
```
void pp2d_set_3D(int enable)
{
	gfxSet3D(enable);
}
```
I need that function to port TWLoader to pp2d  
Thanks!

**Comment by BernardoGiordano** [comment]
Sure! I'll add it as soon as possible.

**Comment by Jolty95** [comment]
@BernardoGiordano Thanks! I didn't wanted to use gfxSet3D (just to make all code look similar) :P
