### ISSUE TITLE
Load PNG from buffer

### ISSUE THREAD

**Issue by ErmanSayin** [BernardoGiordano/pp2d#8]
A function to load PNG from buffer would be nice.

**Comment by BernardoGiordano** [comment]
It already exist

**Comment by BernardoGiordano** [comment]
pp2d_load_texture_memory

**Comment by ErmanSayin** [comment]
That loads from raw texture data, I need a function for loading PNG data in memory. I can do a PR if you want

**Comment by BernardoGiordano** [comment]
If you feel to do it, make a PR and I'll eventually accept it
